### ISSUE TITLE
`tz_context.h` must not be selected for projects configured with TrustZone disabled

### ISSUE THREAD

**Issue by jkrech** [ARM-software/CMSIS_6#201]
Problem: When configuring a project for a device that supports trustzone but with trustzone turned "off" for the project, the `ARM::CMSIS:CORE` must not add the file `CMSIS/Core/Include/tz_context.h` to the list of header files.

```
project:
  processor:
    trustzone: off
    
  components:
    - component: ARM::CMSIS:CORE
```
-> cbuild.yml
```
  components:
    - component: ARM::CMSIS:CORE@6.1.0
      files:
        - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/Core/Include/tz_context.h
          category: header
          version: 6.1.0
```

How to solve it:
https://github.com/ARM-software/CMSIS_6/blob/8c4dc58928b3347f6aa98b6fb2bf6770f32a72b7/ARM.CMSIS.pdsc#L650-L656

tz_context.h uses the condition `TrustZone`
https://github.com/ARM-software/CMSIS_6/blob/8c4dc58928b3347f6aa98b6fb2bf6770f32a72b7/ARM.CMSIS.pdsc#L617-L620

This condition needs to be extended to also check whether the project has TrustZone enabled (`trustzone: on`)
```
    <condition id="TrustZone">
      <description>TrustZone</description>
      <require Dtz="TZ"/>
      <deny Dsecure="TZ-disabled"/>
    </condition>
```

originally raised here: https://github.com/Open-CMSIS-Pack/devtools/issues/1800
